module.exports = [
['Sessions','9:00 AM','Casper 103B','Aaron Salmon','Tent','300','Design deliverables and tips for rapid development'],
['Sessions','9:00 AM','Casper 103A','Vince Bullinger','Console','200','Cross-Platform Mobile Development with React Native'],
['Sessions','9:00 AM','RCU 101','Jim Argeropoulos','Console', '200', 'Leveraging ES6 Promises, Functional Programming, and lodash to Flatten Your Codebase'],
['Sessions','10:15 AM','Casper 103B','Emily Mikl','Tent','100','What Every Developer Needs to Know When Working with Designers'],
['Sessions','10:15 AM','Casper 103A','Jim Poulakos','Console','200','So You Want to Build an Angular App in ES2015'],
['Sessions','10:15 AM','RCU 101','Ben Anderson','Compass','100','Introduction to Flux: A Unidirectional Data Flow Architecture'],
['Sessions','12:45 PM','Casper 103B','Matt Mickelson','Tent','400','Evolving into a Full Stack Engineer'],
['Sessions','12:45 PM','Casper 103A','John Urberg','Console','100','AngularJS Best Practices'],
['Sessions','12:45 PM','RCU 101','Shawn Peters & Jake Schultz','Compass','300','Lessons learned: Building a Test Case Management Tool from Scratch'],
['Sessions','2:00 PM','Casper 103B','James McDougall','Tent','200','Creating a culture and a practice of creativity'],
['Sessions','2:00 PM','Casper 103A','Cory LaNou','Console','200','Go: A One Hour Bootcamp to Build Three Apps'],
['Sessions','2:00 PM','RCU 101','Jason Bock','Compass','200','Esoteric Programming Languages'],
['Sessions','3:15 PM','Casper 103B','Brian Hogan','Tent','400','Contribute To Open Source Software'],
['Sessions','3:15 PM','Casper 103A','Nick Weber','Console','100','IdentityServer vs Auth0'],
['Sessions','3:15 PM','RCU 101','Jason Bock ','Compass','100','What\'s New in C#6'],
['Speakers','9:00 AM','Casper 103B','Aaron Salmon','Tent','300','Design deliverables and tips for rapid development'],
['Speakers','9:00 AM','Casper 103A','Vince Bullinger','Console','200','Cross-Platform Mobile Development with React Native'],
['Speakers','9:00 AM','RCU 101','Jim Argeropoulos','Leveraging ES6 Promises, Functional Programming, and lodash to Flatten Your Codebase'],
['Speakers','10:15 AM','Casper 103B','Emily Mikl','Tent','100','What Every Developer Needs to Know When Working with Designers'],
['Speakers','10:15 AM','Casper 103A','Jim Poulakos','Console','200','So You Want to Build an Angular App in ES2015'],
['Speakers','10:15 AM','RCU 101','Ben Anderson','Compass','100','Introduction to Flux: A Unidirectional Data Flow Architecture'],
['Speakers','12:45 PM','Casper 103B','Matt Mickelson','Tent','400','Evolving into a Full Stack Engineer'],
['Speakers','12:45 PM','Casper 103A','John Urberg','Console','100','AngularJS Best Practices'],
['Speakers','12:45 PM','RCU 101','Shawn Peters & Jake Schultz','Compass','300','Lessons learned: Building a Test Case Management Tool from Scratch'],
['Speakers','2:00 PM','Casper 103B','James McDougall','Tent','200','Creating a culture and a practice of creativity'],
['Speakers','2:00 PM','Casper 103A','Cory LaNou','Console','200','Go: A One Hour Bootcamp to Build Three Apps'],
['Speakers','2:00 PM','RCU 101','Jason Bock','Compass','200','Esoteric Programming Languages'],
['Speakers','3:15 PM','Casper 103B','Brian Hogan','Tent','400','Contribute To Open Source Software'],
['Speakers','3:15 PM','Casper 103A','Nick Weber','Console','100','IdentityServer vs Auth0'],
['Speakers','3:15 PM','RCU 101','Jason Bock ','Compass','100','What\'s New in C#6'],
['Tracks','9:00 AM','Casper 103B','Aaron Salmon','Tent','300','Design deliverables and tips for rapid development'],
['Tracks','9:00 AM','Casper 103A','Vince Bullinger','Console','200','Cross-Platform Mobile Development with React Native'],
['Tracks','9:00 AM','RCU 101','Jim Argeropoulos','Leveraging ES6 Promises, Functional Programming, and lodash to Flatten Your Codebase'],
['Tracks','10:15 AM','Casper 103B','Emily Mikl','Tent','100','What Every Developer Needs to Know When Working with Designers'],
['Tracks','10:15 AM','Casper 103A','Jim Poulakos','Console','200','So You Want to Build an Angular App in ES2015'],
['Tracks','10:15 AM','RCU 101','Ben Anderson','Compass','100','Introduction to Flux: A Unidirectional Data Flow Architecture'],
['Tracks','12:45 PM','Casper 103B','Matt Mickelson','Tent','400','Evolving into a Full Stack Engineer'],
['Tracks','12:45 PM','Casper 103A','John Urberg','Console','100','AngularJS Best Practices'],
['Tracks','12:45 PM','RCU 101','Shawn Peters & Jake Schultz','Compass','300','Lessons learned: Building a Test Case Management Tool from Scratch'],
['Tracks','2:00 PM','Casper 103B','James McDougall','Tent','200','Creating a culture and a practice of creativity'],
['Tracks','2:00 PM','Casper 103A','Cory LaNou','Console','200','Go: A One Hour Bootcamp to Build Three Apps'],
['Tracks','2:00 PM','RCU 101','Jason Bock','Compass','200','Esoteric Programming Languages'],
['Tracks','3:15 PM','Casper 103B','Brian Hogan','Tent','400','Contribute To Open Source Software'],
['Tracks','3:15 PM','Casper 103A','Nick Weber','Console','100','IdentityServer vs Auth0'],
['Tracks','3:15 PM','RCU 101','Jason Bock ','Compass','100','What\'s New in C#6']];