module.exports = [['Sessions','9:15 AM','P0806A','Joel Crabb','Tent','300','Do Something Unbelievably Stupid—Become a Software Engineering Manager!'],
['Sessions','9:15 AM','P0808A','Jenn Strater','Console','200','Introduction to Groovy'],
['Sessions','9:15 AM','P0808B','Mac Noland','Compass','200','Massively Scalable Web Analytics Using Apache Hadoop'],
['Sessions','9:15 AM','P0806B','Chad Brovold','Signs','200','Building to Scale: Developing Your Stack for High Availability'],
['Sessions','9:15 AM','P0838','Matt Ruby','Graph','400','Practical ReactJS'],
['Sessions','10:35 AM','P0806A','Jamie Thingelstad','Tent','100','Transforming Your Organization with Open Source'],
['Sessions','10:35 AM','P0808A','Matthew Tift','Console','200','Introducing Drupal 8'],
['Sessions','10:35 AM','P0808B','Aaron Strey','Compass','100','Apache Kafka @ Target'],
['Sessions','10:35 AM','P0806B','Charles Betz','Signs','200','DevOps in a Box: a Vagrant-Based Continuous Delivery Pipeline on Your Workstation'],
['Sessions','10:35 AM','P0838','Ilya Verbitskiy','Graph','200','Node.js Security'],
['Sessions','12:35 PM','P0806A','James Falkner','Tent','400','Liferay Modernizes the Enterprise Portal Platform'],
['Sessions','12:35 PM','P0808A','Josh Klun','Console','100','Accelerating Scala Development with IntelliJ IDEA'],
['Sessions','12:35 PM','P0808B','Derek Bodin','Compass','300','Improving User Experience with Elastic Search'],
['Sessions','12:35 PM','P0806B','John Young','Signs','300','Building Internet of Things with Open Source Software and Hardware'],
['Sessions','12:35 PM','P0838','Jim Cummins','Graph','200','Getting Started with Angular 2 and TypeScript'],
['Sessions','1:55 PM','P0806A','Randall Larson','Tent','200','5 Things You Can Do to Get People Excited about Your Idea'],
['Sessions','1:55 PM','P0808A','Matt Gray','Console','200','Inspiring a Code Savvy Generation at CoderDojoTC'],
['Sessions','1:55 PM','P0808B','Damodar Chetty','Compass','200','Database Evolution — from Relational to NoSQL'],
['Sessions','1:55 PM','P0806B','Mike Willbanks','Signs','300','Service-Oriented Architecture as a Pattern of Development'],
['Sessions','1:55 PM','P0838','Aaron Ackerman','Graph','200','Future JavaScript Syntax in Current Browsers with Babel'],
['Sessions','3:15 PM','P0806A','David Washington','Tent','400','Microsoft Open Source Strategy'],
['Sessions','3:15 PM','P0808A','Vince Bullinger','Console','100','Cross-Platform Mobile Development with React Native'],
['Sessions','3:15 PM','P0808B','Steve Finck','Compass','100','Bootiful Mongo'],
['Sessions','3:15 PM','P0806B','Luke Bredeson','Signs','300','Binary Protocols and You'],
['Sessions','3:15 PM','P0838','Jay Landro','Graph','200','Frontin — Integrating Front-End Build Tools into Your Back-End Builds'],
['Speakers','9:15 AM','P0806A','Joel Crabb','Tent','300','Do Something Unbelievably Stupid—Become a Software Engineering Manager!'],
['Speakers','9:15 AM','P0808A','Jenn Strater','Console','200','Introduction to Groovy'],
['Speakers','9:15 AM','P0808B','Mac Noland','Compass','200','Massively Scalable Web Analytics Using Apache Hadoop'],
['Speakers','9:15 AM','P0806B','Chad Brovold','Signs','200','Building to Scale: Developing Your Stack for High Availability'],
['Speakers','9:15 AM','P0838','Matt Ruby','Graph','400','Practical ReactJS'],
['Speakers','10:35 AM','P0806A','Jamie Thingelstad','Tent','100','Transforming Your Organization with Open Source'],
['Speakers','10:35 AM','P0808A','Matthew Tift','Console','200','Introducing Drupal 8'],
['Speakers','10:35 AM','P0808B','Aaron Strey','Compass','100','Apache Kafka @ Target'],
['Speakers','10:35 AM','P0806B','Charles Betz','Signs','200','DevOps in a Box: a Vagrant-Based Continuous Delivery Pipeline on Your Workstation'],
['Speakers','10:35 AM','P0838','Ilya Verbitskiy','Graph','200','Node.js Security'],
['Speakers','12:35 PM','P0806A','James Falkner','Tent','400','Liferay Modernizes the Enterprise Portal Platform'],
['Speakers','12:35 PM','P0808A','Josh Klun','Console','100','Accelerating Scala Development with IntelliJ IDEA'],
['Speakers','12:35 PM','P0808B','Derek Bodin','Compass','300','Improving User Experience with Elastic Search'],
['Speakers','12:35 PM','P0806B','John Young','Signs','300','Building Internet of Things with Open Source Software and Hardware'],
['Speakers','12:35 PM','P0838','Jim Cummins','Graph','200','Getting Started with Angular 2 and TypeScript'],
['Speakers','1:55 PM','P0806A','Randall Larson','Tent','200','5 Things You Can Do to Get People Excited about Your Idea'],
['Speakers','1:55 PM','P0808A','Matt Gray','Console','200','Inspiring a Code Savvy Generation at CoderDojoTC'],
['Speakers','1:55 PM','P0808B','Damodar Chetty','Compass','200','Database Evolution — from Relational to NoSQL'],
['Speakers','1:55 PM','P0806B','Mike Willbanks','Signs','300','Service-Oriented Architecture as a Pattern of Development'],
['Speakers','1:55 PM','P0838','Aaron Ackerman','Graph','200','Future JavaScript Syntax in Current Browsers with Babel'],
['Speakers','3:15 PM','P0806A','David Washington','Tent','400','Microsoft Open Source Strategy'],
['Speakers','3:15 PM','P0808A','Vince Bullinger','Console','100','Cross-Platform Mobile Development with React Native'],
['Speakers','3:15 PM','P0808B','Steve Finck','Compass','100','Bootiful Mongo'],
['Speakers','3:15 PM','P0806B','Luke Bredeson','Signs','300','Binary Protocols and You'],
['Speakers','3:15 PM','P0838','Jay Landro','Graph','200','Frontin — Integrating Front-End Build Tools into Your Back-End Builds'],
['Tracks','9:15 AM','P0806A','Joel Crabb','Tent','300','Do Something Unbelievably Stupid—Become a Software Engineering Manager!'],
['Tracks','9:15 AM','P0808A','Jenn Strater','Console','200','Introduction to Groovy'],
['Tracks','9:15 AM','P0808B','Mac Noland','Compass','200','Massively Scalable Web Analytics Using Apache Hadoop'],
['Tracks','9:15 AM','P0806B','Chad Brovold','Signs','200','Building to Scale: Developing Your Stack for High Availability'],
['Tracks','9:15 AM','P0838','Matt Ruby','Graph','400','Practical ReactJS'],
['Tracks','10:35 AM','P0806A','Jamie Thingelstad','Tent','100','Transforming Your Organization with Open Source'],
['Tracks','10:35 AM','P0808A','Matthew Tift','Console','200','Introducing Drupal 8'],
['Tracks','10:35 AM','P0808B','Aaron Strey','Compass','100','Apache Kafka @ Target'],
['Tracks','10:35 AM','P0806B','Charles Betz','Signs','200','DevOps in a Box: a Vagrant-Based Continuous Delivery Pipeline on Your Workstation'],
['Tracks','10:35 AM','P0838','Ilya Verbitskiy','Graph','200','Node.js Security'],
['Tracks','12:35 PM','P0806A','James Falkner','Tent','400','Liferay Modernizes the Enterprise Portal Platform'],
['Tracks','12:35 PM','P0808A','Josh Klun','Console','100','Accelerating Scala Development with IntelliJ IDEA'],
['Tracks','12:35 PM','P0808B','Derek Bodin','Compass','300','Improving User Experience with Elastic Search'],
['Tracks','12:35 PM','P0806B','John Young','Signs','300','Building Internet of Things with Open Source Software and Hardware'],
['Tracks','12:35 PM','P0838','Jim Cummins','Graph','200','Getting Started with Angular 2 and TypeScript'],
['Tracks','1:55 PM','P0806A','Randall Larson','Tent','200','5 Things You Can Do to Get People Excited about Your Idea'],
['Tracks','1:55 PM','P0808A','Matt Gray','Console','200','Inspiring a Code Savvy Generation at CoderDojoTC'],
['Tracks','1:55 PM','P0808B','Damodar Chetty','Compass','200','Database Evolution — from Relational to NoSQL'],
['Tracks','1:55 PM','P0806B','Mike Willbanks','Signs','300','Service-Oriented Architecture as a Pattern of Development'],
['Tracks','1:55 PM','P0838','Aaron Ackerman','Graph','200','Future JavaScript Syntax in Current Browsers with Babel'],
['Tracks','3:15 PM','P0806A','David Washington','Tent','400','Microsoft Open Source Strategy'],
['Tracks','3:15 PM','P0808A','Vince Bullinger','Console','100','Cross-Platform Mobile Development with React Native'],
['Tracks','3:15 PM','P0808B','Steve Finck','Compass','100','Bootiful Mongo'],
['Tracks','3:15 PM','P0806B','Luke Bredeson','Signs','300','Binary Protocols and You'],
['Tracks','3:15 PM','P0838','Jay Landro','Graph','200','Frontin — Integrating Front-End Build Tools into Your Back-End Builds']
];