module.exports = [
['Sessions','8:30 AM','Rapson 100','Jeffrey Rondeau','Tent','300','AntiPatterns: Avoiding the Traps of Bad Design'],
['Sessions','8:30 AM','Rapson 31','Brad Broulik','Console','200','Apple TV Developer Kit'],
['Sessions','8:30 AM','Rapson 43','Riley Major','Compass','200','SQL Server 2016 - New Feature Preview'],
['Sessions','8:30 AM','Rapson 45','Mac Noland','Signs','200','Web Analytics on Hadoop'],
['Sessions','8:30 AM','Rapson 54','Torsten Muller','Graph','400','Functional Reactive Programming with Rx.js'],
['Sessions','8:30 AM','Rapson 56','Benjamin Xue','Graph','400','Get Started with your Healthcare IoT Project with Microsoft Band'],
['Sessions','8:30 AM','Rapson 58','Sunil Ayyapankutty, Praveen Addepally and Anibal Velarde','Graph','400','Building a Secure, Low-Budget IAM/SSO Service'],
['Sessions','9:45 AM','Rapson 100','Tim VanFosson','Tent','100','Automated Tests: Patterns and Practices'],
['Sessions','9:45 AM','Rapson 31','Jennifer Simon','Console','200','Networking 101: How to Network with People and not Computers'],
['Sessions','9:45 AM','Rapson 43','Brock Noland','Compass','100','Real-Time Analytics on IoT Sensors Using Apache Kafka and Spark'],
['Sessions','9:45 AM','Rapson 45','Maggie Pint','Signs','200','Got Documents? An Exploration of Document Databases in Software Architecture'],
['Sessions','9:45 AM','Rapson 54','Martin Hertz','Graph','200','Technical Debt: From Acceptance to Action'],
['Sessions','9:45 AM','Rapson 56','Jason Bock','Graph','400','Dependencies Demystified'],
['Sessions','9:45 AM','Rapson 58','Tom Soderling','Graph','400','Apple Watch Development with the Xamarin Watch Kit'],
['Sessions','11:00 AM','Rapson 100','Dan Callahan','Tent','400','Mastering Asynchronous JavaScript'],
['Sessions','11:00 AM','Rapson 31','Vince Bullinger','Console','100','Cross-Platform Mobile Development with React Native'],
['Sessions','11:00 AM','Rapson 43','Zach Wendt','Compass','300','VR Design and Unity Crash Course for Developers'],
['Sessions','11:00 AM','Rapson 45','Brad Broulik','Signs','300','UI Testing iOS & Android Apps'],
['Sessions','11:00 AM','Rapson 54','Dan Nordquist','Graph','200','DevOps and the Microsoft Developer Community'],
['Sessions','11:00 AM','Rapson 56','Mike Benkovich','Graph','400','Tame the Mobile Jungle to Build Cross-Platform Connected Solutions with Visual Studio 2015 and Azure'],
['Sessions','11:00 AM','Rapson 58','Justin Chase','Graph','400','How I Learned to Stop Worrying About Cross-Platform and Love Electron'],
['Sessions','1:00 PM','Rapson 100','John Culviner','Tent','200','Node.js & MongoDB API: Fully Tested, from Scratch'],
['Sessions','1:00 PM','Rapson 31','Kamran Ayub','Console','200','Demystifying Typescript'],
['Sessions','1:00 PM','Rapson 43','Jason Motylinski','Compass','200','Data Engineering 101: Building Data Pipelines with Luigi'],
['Sessions','1:00 PM','Rapson 45','Mike Hodnick','Signs','300','Programming as Live Performance Art'],
['Sessions','1:00 PM','Rapson 54','Jeremy Wagner','Graph','200','The Flexbox Cometh: Champion of the Layout'],
['Sessions','1:00 PM','Rapson 56','Shawn Peters & Jake Schultz','Graph','400','To Test a Tool to Test Your Project'],
['Sessions','1:00 PM','Rapson 58','Maggie Pint','Graph','400','Your DBA Says It Depends. Now What?'],
['Sessions','2:15 PM','Rapson 100','Brian Hogan and Chris Johnson','Tent','400','Build a Real-Time App Using Elixir and Angular'],
['Sessions','2:15 PM','Rapson 31','Scott Davis','Console','100','Xamarin: Cross-Platform Beyond the Generic Buttons and Text Boxes'],
['Sessions','2:15 PM','Rapson 43','Rocky Lhotka','Compass','100','Build Distributed Business Apps Using CSLA.Net'],
['Sessions','2:15 PM','Rapson 45','Dave Strebel','Signs','300','12-Factor Apps, Microservices, PaaS, Oh My!'],
['Sessions','2:15 PM','Rapson 54','TechMasters','Graph','200','Improve Your Technical Public-Speaking Skills with Toastmasters'],
['Sessions','2:15 PM','Rapson 56','Jake Good','Graph','400','Lightning Talks'],
['Sessions','2:15 PM','Rapson 58','Mohamed Kishawy','Graph','400','Move to the Cloud with Bluemix'],





['Speakers','8:30 AM','Rapson 100','Jeffrey Rondeau','Tent','300','AntiPatterns: Avoiding the Traps of Bad Design'],
['Speakers','8:30 AM','Rapson 31','Brad Broulik','Console','200','Apple TV Developer Kit'],
['Speakers','8:30 AM','Rapson 43','Riley Major','Compass','200','SQL Server 2016 - New Feature Preview'],
['Speakers','8:30 AM','Rapson 45','Mac Noland','Signs','200','Web Analytics on Hadoop'],
['Speakers','8:30 AM','Rapson 54','Torsten Muller','Graph','400','Functional Reactive Programming with Rx.js'],
['Speakers','8:30 AM','Rapson 56','Benjamin Xue','Graph','400','Get Started with your Healthcare IoT Project with Microsoft Band'],
['Speakers','8:30 AM','Rapson 58','Sunil Ayyapankutty, Praveen Addepally and Anibal Velarde','Graph','400','Building a Secure, Low-Budget IAM/SSO Service'],
['Speakers','9:45 AM','Rapson 100','Tim VanFosson','Tent','100','Automated Tests: Patterns and Practices'],
['Speakers','9:45 AM','Rapson 31','Jennifer Simon','Console','200','Networking 101: How to Network with People and not Computers'],
['Speakers','9:45 AM','Rapson 43','Brock Noland','Compass','100','Real-Time Analytics on IoT Sensors Using Apache Kafka and Spark'],
['Speakers','9:45 AM','Rapson 45','Maggie Pint','Signs','200','Got Documents? An Exploration of Document Databases in Software Architecture'],
['Speakers','9:45 AM','Rapson 54','Martin Hertz','Graph','200','Technical Debt: From Acceptance to Action'],
['Speakers','9:45 AM','Rapson 56','Jason Bock','Graph','400','Dependencies Demystified'],
['Speakers','9:45 AM','Rapson 58','Tom Soderling','Graph','400','Apple Watch Development with the Xamarin Watch Kit'],
['Speakers','11:00 AM','Rapson 100','Dan Callahan','Tent','400','Mastering Asynchronous JavaScript'],
['Speakers','11:00 AM','Rapson 31','Vince Bullinger','Console','100','Cross-Platform Mobile Development with React Native'],
['Speakers','11:00 AM','Rapson 43','Zach Wendt','Compass','300','VR Design and Unity Crash Course for Developers'],
['Speakers','11:00 AM','Rapson 45','Brad Broulik','Signs','300','UI Testing iOS & Android Apps'],
['Speakers','11:00 AM','Rapson 54','Dan Nordquist','Graph','200','DevOps and the Microsoft Developer Community'],
['Speakers','11:00 AM','Rapson 56','Mike Benkovich','Graph','400','Tame the Mobile Jungle to Build Cross-Platform Connected Solutions with Visual Studio 2015 and Azure'],
['Speakers','11:00 AM','Rapson 58','Justin Chase','Graph','400','How I Learned to Stop Worrying About Cross-Platform and Love Electron'],
['Speakers','1:00 PM','Rapson 100','John Culviner','Tent','200','Node.js & MongoDB API: Fully Tested, from Scratch'],
['Speakers','1:00 PM','Rapson 31','Kamran Ayub','Console','200','Demystifying Typescript'],
['Speakers','1:00 PM','Rapson 43','Jason Motylinski','Compass','200','Data Engineering 101: Building Data Pipelines with Luigi'],
['Speakers','1:00 PM','Rapson 45','Mike Hodnick','Signs','300','Programming as Live Performance Art'],
['Speakers','1:00 PM','Rapson 54','Jeremy Wagner','Graph','200','The Flexbox Cometh: Champion of the Layout'],
['Speakers','1:00 PM','Rapson 56','Shawn Peters & Jake Schultz','Graph','400','To Test a Tool to Test Your Project'],
['Speakers','1:00 PM','Rapson 58','Maggie Pint','Graph','400','Your DBA Says It Depends. Now What?'],
['Speakers','2:15 PM','Rapson 100','Brian Hogan and Chris Johnson','Tent','400','Build a Real-Time App Using Elixir and Angular'],
['Speakers','2:15 PM','Rapson 31','Scott Davis','Console','100','Xamarin: Cross-Platform Beyond the Generic Buttons and Text Boxes'],
['Speakers','2:15 PM','Rapson 43','Rocky Lhotka','Compass','100','Build Distributed Business Apps Using CSLA.Net'],
['Speakers','2:15 PM','Rapson 45','Dave Strebel','Signs','300','12-Factor Apps, Microservices, PaaS, Oh My!'],
['Speakers','2:15 PM','Rapson 54','TechMasters','Graph','200','Improve Your Technical Public-Speaking Skills with Toastmasters'],
['Speakers','2:15 PM','Rapson 56','Jake Good','Graph','400','Lightning Talks'],
['Speakers','2:15 PM','Rapson 58','Mohamed Kishawy','Graph','400','Move to the Cloud with Bluemix'],




['Tracks','8:30 AM','Rapson 100','Jeffrey Rondeau','Tent','300','AntiPatterns: Avoiding the Traps of Bad Design'],
['Tracks','8:30 AM','Rapson 31','Brad Broulik','Console','200','Apple TV Developer Kit'],
['Tracks','8:30 AM','Rapson 43','Riley Major','Compass','200','SQL Server 2016 - New Feature Preview'],
['Tracks','8:30 AM','Rapson 45','Mac Noland','Signs','200','Web Analytics on Hadoop'],
['Tracks','8:30 AM','Rapson 54','Torsten Muller','Graph','400','Functional Reactive Programming with Rx.js'],
['Tracks','8:30 AM','Rapson 56','Benjamin Xue','Graph','400','Get Started with your Healthcare IoT Project with Microsoft Band'],
['Tracks','8:30 AM','Rapson 58','Sunil Ayyapankutty, Praveen Addepally and Anibal Velarde','Graph','400','Building a Secure, Low-Budget IAM/SSO Service'],
['Tracks','9:45 AM','Rapson 100','Tim VanFosson','Tent','100','Automated Tests: Patterns and Practices'],
['Tracks','9:45 AM','Rapson 31','Jennifer Simon','Console','200','Networking 101: How to Network with People and not Computers'],
['Tracks','9:45 AM','Rapson 43','Brock Noland','Compass','100','Real-Time Analytics on IoT Sensors Using Apache Kafka and Spark'],
['Tracks','9:45 AM','Rapson 45','Maggie Pint','Signs','200','Got Documents? An Exploration of Document Databases in Software Architecture'],
['Tracks','9:45 AM','Rapson 54','Martin Hertz','Graph','200','Technical Debt: From Acceptance to Action'],
['Tracks','9:45 AM','Rapson 56','Jason Bock','Graph','400','Dependencies Demystified'],
['Tracks','9:45 AM','Rapson 58','Tom Soderling','Graph','400','Apple Watch Development with the Xamarin Watch Kit'],
['Tracks','11:00 AM','Rapson 100','Dan Callahan','Tent','400','Mastering Asynchronous JavaScript'],
['Tracks','11:00 AM','Rapson 31','Vince Bullinger','Console','100','Cross-Platform Mobile Development with React Native'],
['Tracks','11:00 AM','Rapson 43','Zach Wendt','Compass','300','VR Design and Unity Crash Course for Developers'],
['Tracks','11:00 AM','Rapson 45','Brad Broulik','Signs','300','UI Testing iOS & Android Apps'],
['Tracks','11:00 AM','Rapson 54','Dan Nordquist','Graph','200','DevOps and the Microsoft Developer Community'],
['Tracks','11:00 AM','Rapson 56','Mike Benkovich','Graph','400','Tame the Mobile Jungle to Build Cross-Platform Connected Solutions with Visual Studio 2015 and Azure'],
['Tracks','11:00 AM','Rapson 58','Justin Chase','Graph','400','How I Learned to Stop Worrying About Cross-Platform and Love Electron'],
['Tracks','1:00 PM','Rapson 100','John Culviner','Tent','200','Node.js & MongoDB API: Fully Tested, from Scratch'],
['Tracks','1:00 PM','Rapson 31','Kamran Ayub','Console','200','Demystifying Typescript'],
['Tracks','1:00 PM','Rapson 43','Jason Motylinski','Compass','200','Data Engineering 101: Building Data Pipelines with Luigi'],
['Tracks','1:00 PM','Rapson 45','Mike Hodnick','Signs','300','Programming as Live Performance Art'],
['Tracks','1:00 PM','Rapson 54','Jeremy Wagner','Graph','200','The Flexbox Cometh: Champion of the Layout'],
['Tracks','1:00 PM','Rapson 56','Shawn Peters & Jake Schultz','Graph','400','To Test a Tool to Test Your Project'],
['Tracks','1:00 PM','Rapson 58','Maggie Pint','Graph','400','Your DBA Says It Depends. Now What?'],
['Tracks','2:15 PM','Rapson 100','Brian Hogan and Chris Johnson','Tent','400','Build a Real-Time App Using Elixir and Angular'],
['Tracks','2:15 PM','Rapson 31','Scott Davis','Console','100','Xamarin: Cross-Platform Beyond the Generic Buttons and Text Boxes'],
['Tracks','2:15 PM','Rapson 43','Rocky Lhotka','Compass','100','Build Distributed Business Apps Using CSLA.Net'],
['Tracks','2:15 PM','Rapson 45','Dave Strebel','Signs','300','12-Factor Apps, Microservices, PaaS, Oh My!'],
['Tracks','2:15 PM','Rapson 54','TechMasters','Graph','200','Improve Your Technical Public-Speaking Skills with Toastmasters'],
['Tracks','2:15 PM','Rapson 56','Jake Good','Graph','400','Lightning Talks'],
['Tracks','2:15 PM','Rapson 58','Mohamed Kishawy','Graph','400','Move to the Cloud with Bluemix']];