module.exports = [['Monday','10:30 AM','C','David Hoerster','Cloud','300','Event Sourcing Baseball History'],
['Monday','10:30 AM','G','Aaron Erickson','Other','200','From the Abyss to Nirvana - Moving Towards Sane Software Development'],
['Monday','10:30 AM','Portia','Bermon Painter','Web','200','Front-End Workflows with Gulp'],
['Monday','10:30 AM','E','Keith Wedinger','Mobile','200','Implementing Push Notification Support in your Android App'],
['Monday','10:30 AM','Aralia','Shaunak Kashyap','Web','400','Introduction to Elasticsearch'],
['Monday','10:30 AM','F','Erik Weber','Other','400','Leadership: Practiced.'],
['Monday','10:30 AM','Wisteria','Ilya Verbitskiy','Web','300','Node.js Security'],
['Monday','10:30 AM','Tamarind','Benjamin Finkel','Cloud','300','Old IT Pros, New Tricks - Why, and How, You Should Learn Google Cloud'],
['Monday','10:30 AM','B','Jimmy Bogard','Web','300','Put Your Controllers On A Diet'],
['Monday','10:30 AM','D','Spencer Schneidenbach','Mobile','200','Real-Time Cross-Platform Mobile Apps using Xamarin and SignalR'],
['Monday','10:30 AM','Guava','G. Andrew Duthie','Other','200','See me, Feel me, Touch me. Sensors and the Internet of Things'],
['Monday','10:30 AM','Marula','Jeff McWherter','Other','100','Thats It, Ive had enough, Im starting my own company'],
['Monday','10:30 AM','Mess Hall','Richard Campbell','Family','100','The Family Keynote'],
['Monday','1:00 PM','D','John Ptacek','Web','300','AngularJS directives and the Spiderman credo; with great power comes great responsibility'],
['Monday','1:00 PM','F','David Berry','Other','100','Becoming a Lifelong Learner. Taking Control of Your Future Through Effective Personal Development'],
['Monday','1:00 PM','G','Cory House','Web','200','Dawn of the Reusable Web: Diving into Web Components'],
['Monday','1:00 PM','Guava','Chris Powers','Other','100','Developer to Manager: Finding Your Path and Passion'],
['Monday','1:00 PM','Aralia','Sam Basu','Mobile','200','Introduction to NativeScript!'],
['Monday','1:00 PM','B','Bill Wagner','Other','200','LINQ Workshop: Understanding the Magic of it all'],
['Monday','1:00 PM','E','Kirsten Hunter','Mobile','400','Quantifying your Health'],
['Monday','1:00 PM','Mangrove','William Wallace','Other','100','Save That Random Universe (ALL DAY)'],
['Monday','1:00 PM','C','Eric Boyd','Cloud','200','Setting Up Your First VM, and Maybe Your Data Center, In Azure'],
['Monday','1:00 PM','Portia','JC Grubbs','Other','200','Stopping a Slow Motion Trainwreck: A guide to project recovery.'],
['Monday','1:00 PM','Wisteria','Tony Gemoll','Web','300','Stories of Web Audio by the Campfire'],
['Monday','1:00 PM','Tamarind','Carl Schweitzer','Mobile','200','Welcoming the new camper: Windows 10'],
['Monday','1:00 PM','Marula','Keith Elder','Cloud','100','Why Erlang'],
['Monday','2:30 PM','Guava','David Washington','Mobile','400','Building touch experiences that dont suck'],
['Monday','2:30 PM','Mess Hall','Kris Boedigheimer','Family','100','Camp Fun and Games with Paper Airplanes'],
['Monday','2:30 PM','Iron Wood','Matt Schmidt','Family','300','Code a Copter - Write Code to Control a Helicopter'],
['Monday','2:30 PM','E','Brian Lagunas','Mobile','300','Creating Cross Platform Games with Unity'],
['Monday','2:30 PM','B','David Calavera','Cloud','200','Docker inside out'],
['Monday','2:30 PM','C','Ryan Niemeyer','Web','200','Dont Forget the Bug Spray: JavaScript Debugging Techniques'],
['Monday','2:30 PM','Tamarind','Dan Lorenz','Web','100','Gazing at the new JavaScript framework star, Aurelia'],
['Monday','2:30 PM','G','Keith Casey','Other','300','Is your API Misbehaving?'],
['Monday','2:30 PM','Portia','Sam Basu','Web','100','Kendo UI 101'],
['Monday','2:30 PM','Marula','Greg Levenhagen','Mobile','200','One UI to Rule them All with Universal Apps and Xamarin Forms'],
['Monday','2:30 PM','Banyan','Ashlyn Larsen','Family','400','Protect your Minecraft Campsite with Traps and Tricks using Command Blocks!'],
['Monday','2:30 PM','D','Brian Rinaldi','Web','100','Theyre Back! - Modern Tools for Static Site Development'],
['Monday','2:30 PM','Cypress','Michael Blumenthal','Family','100','Tools to Teach Kids to Code'],
['Monday','2:30 PM','F','Jason Bock','Other','200','Whats New in C#6'],
['Monday','4:00 PM','E','Cory House','Web','200','Angular, Backbone, and Knockout are Great. So Why Choose React?'],
['Monday','4:00 PM','Portia','Matt Kremer','Other','200','Building Software Products in a Weekend (Really)'],
['Monday','4:00 PM','Wisteria','Todd Gardner','Other','200','Case Studies in Terrible Testing'],
['Monday','4:00 PM','Iron Wood','Matt Schmidt','Family','300','Code a Copter - Write Code to Control a Helicopter'],
['Monday','4:00 PM','Guava','Russ Unger','Web','200','DesignOps Skunk Works - Shoes for the Cobblers Children'],
['Monday','4:00 PM','Banyan','Richard Campbell','Family','400','Internet Safety for Parents and Kids'],
['Monday','4:00 PM','Marula','Elizabeth Groom','Other','100','Intro to R from a C# developer'],
['Monday','4:00 PM','B','Brian Korzynski','Cloud','100','Introduction to Amazon AWS'],
['Monday','4:00 PM','Cypress','Scott Fradkin','Family','300','Introduction to Sonic Pi'],
['Monday','4:00 PM','F','Brandon Martinez','Web','200','Make a SASSy CSS Cocktail: Bourbon and Bitters Served Neat'],
['Monday','4:00 PM','Tamarind','Amir Rajan','Mobile','400','Making it to the #1 Spot in the App Store'],
['Monday','4:00 PM','D','Joe Eames','Web','300','Stronger, Smarter, Faster: Angular 2'],
['Monday','4:00 PM','G','Mike Clement','Other','200','The Quest for Continuous Delivery'],
['Monday','4:00 PM','C','Edward Brey','Mobile','200','Tie modern mobile apps to crusty backends with Protocol Buffers'],
['Tuesday','10:30 AM','Guava','Eli White','Cloud','300','Amazon SimpleDB'],
['Tuesday','10:30 AM','C','Jeremiah Billmann','Web','300','Building Isomorphic JavaScript Applications with React and Node.js'],
['Tuesday','10:30 AM','D','Steve Marx','Mobile','200','Do you have the time? No, Im running a different app right now.'],
['Tuesday','10:30 AM','Portia','Chris Johnson','Web','200','Going beyond the Rails "defaults"'],
['Tuesday','10:30 AM','B','Kenny Young','Cloud','400','Keep Campers riding bikes – a lesson in Azure Machine Learning (ML)'],
['Tuesday','10:30 AM','G','Matt Stratton','Other','200','Making Infrastructure Smores with Chef'],
['Tuesday','10:30 AM','Cypress','Michael Wheeler','Family','300','Minecraft Modding  for Junior Campers using Youth Digital'],
['Tuesday','10:30 AM','E','Kevin Hakanson','Web','200','ng-owasp: OWASP Top 10 for AngularJS Applications'],
['Tuesday','10:30 AM','Banyan','Sean Archer','Family','100','Stamp Camp 3D!'],
['Tuesday','10:30 AM','F','Stephen Cleary','Other','300','Unit Testing Asynchronous Code'],
['Tuesday','10:30 AM','Tamarind','Dan Gartner','Mobile','200','Whats New with Visual Studio 2015: Supercharged Edition!'],
['Tuesday','10:30 AM','Wisteria','Greg Damm','Other','400','Why Working in Enterprise Software Design Doesnt Suck'],
['Tuesday','10:30 AM','Marula','Rob Harr','Other','100','Why your business should have an apprentice program'],
['Tuesday','1:00 PM','F','Jeremy Miller','Web','300','A Field Report on Building an Application with React.js'],
['Tuesday','1:00 PM','B','Lauren Amundson','Cloud','200','A Toe in the Clouds: Hybrid Cloud Solutions with Azure'],
['Tuesday','1:00 PM','C','Matthew Snyder','Mobile','300','Apple Watch Development: The Bear Essentials'],
['Tuesday','1:00 PM','Guava','Lance Larsen','Web','200','HAVE NO FEAR: vNext? MVC 6? ASP.NET 5? VS2015?'],
['Tuesday','1:00 PM','E','Jen Looper','Mobile','200','Into the Woods with your Beacon-powered Mobile App - Micro-Orienteering with Offline-First Design'],
['Tuesday','1:00 PM','G','Chris Gardner','Other','200','Introduction to Game Design'],
['Tuesday','1:00 PM','Wisteria','Brian Genisio','Other','200','JavaScript Robotics? Not a bad idea.'],
['Tuesday','1:00 PM','Cypress','Katelyn Drew','Family','200','Koding for Kids 1.0: K-2nd grade'],
['Tuesday','1:00 PM','D','David Neal','Web','100','Node.js Crash Course'],
['Tuesday','1:00 PM','Mangrove','William Wallace','Other','100','Save That Random Universe (ALL DAY)'],
['Tuesday','1:00 PM','Iron Wood','Benjamin Gavin','Family','300','That Robotics Lab - Day 1'],
['Tuesday','1:00 PM','Portia','Jacqui Senn','Other','400','The Safety in Numbers'],
['Tuesday','1:00 PM','Tamarind','Josh Gretz','Other','300','Time Is Trying To Kill You'],
['Tuesday','1:00 PM','Marula','Jason Groom','Other','400','What is Data Science Anyway? '],
['Tuesday','2:30 PM','Cypress','Sharon Cichelli','Family','100','(More) Circuits in Play Dough'],
['Tuesday','2:30 PM','G','Md Khan','Web','200','Advance JavaScript Debug'],
['Tuesday','2:30 PM','Tamarind','James Bender','Other','200','BDD with Cucumber in .NET with SpecFlow'],
['Tuesday','2:30 PM','D','George Roberts','Mobile','200','Building Windows Apps That Are Universally Loved'],
['Tuesday','2:30 PM','Guava','Christopher Woodruff','Web','300','Discover the RESTier Framework to Produce ASP.NET Web API OData v4 Web Services'],
['Tuesday','2:30 PM','B','Matthew Soucoup','Cloud','100','Everybody Into The Pool! Node.js for .NET Developers'],
['Tuesday','2:30 PM','Marula','Danny Warren','Mobile','200','Hey, Cortana! Where am I?'],
['Tuesday','2:30 PM','F','Jes Borland','Other','300','Level Up Your SQL Server Index Knowledge'],
['Tuesday','2:30 PM','C','Allen Zaudtke','Other','200','Message Queues - Why Should I use them'],
['Tuesday','2:30 PM','Portia','Josh Forde','Web','300','Real-time Multiplayer Game Development with Node.js and Socket.io'],
['Tuesday','2:30 PM','E','Ryan Michela','Other','300','Slaying the monolith dragon - a practical guide to microservices'],
['Tuesday','2:30 PM','Wisteria','Paul Hinze','Cloud','300','Smoke & Mirrors: The Primitives of High Availability'],
['Tuesday','4:00 PM','Wisteria','Cori Drew','Other','200','“The Git Parable” Campfire Story'],
['Tuesday','4:00 PM','G','Dan Kline','Other','400','Are you an explorer?  IoT and Blazing your own trail.'],
['Tuesday','4:00 PM','F','Chris Risner','Web','300','ASP.NET on Linux and Mac: Camping at the Four Seasons'],
['Tuesday','4:00 PM','B','Wade Wegner','Cloud','300','Azure API Apps for Web, Mobile, and Logic Apps'],
['Tuesday','4:00 PM','Guava','Brian Hogan','Other','100','Campers, Meet Elixir!'],
['Tuesday','4:00 PM','C','Godfrey Nolan','Mobile','400','Driveables'],
['Tuesday','4:00 PM','Portia','Jim Wooley','Other','300','Entity Framework performance monitoring and tuning'],
['Tuesday','4:00 PM','Tamarind','Mike Ward','Web','100','GitHub Pages -  Websites for you and your projects'],
['Tuesday','4:00 PM','D','Matthew Ridley','Mobile','300','Isnt It Ionic? Building faster Cordova/PhoneGap applications with the Ionic Framework'],
['Tuesday','4:00 PM','Marula','Dan Piessens','Other','300','Its more than feature toggles: Enabling Applications for Continuous Delivery'],
['Tuesday','4:00 PM','Cypress','Kevin Hakanson','Family','300','Learning to Mod Minecraft: A Father/Daughter Retrospective'],
['Tuesday','4:00 PM','E','Sara Gibbons','Other','400','Working Remote & Parenting, Balancing Both and Still Remembering to Shower'],
['Wednesday','10:30 AM','Wisteria','Alan Mendelevich','Mobile','200','Ads in Mobile Apps and Games 101'],
['Wednesday','10:30 AM','Marula','Heather White','Other','400','Better Understand Your Non-Technical Coworkers'],
['Wednesday','10:30 AM','Guava','Morgan McCrory','Other','400','Code She Wrote'],
['Wednesday','10:30 AM','C','Ondrej Balas','Cloud','100','Creating Scalable Solutions with Amazon Cloud Services'],
['Wednesday','10:30 AM','Tamarind','Mike Kuphal','Other','100','Dont Prepare, Just Show Up!'],
['Wednesday','10:30 AM','Banyan','Katarina Eames','Family','100','Getting Kids Interested in Angular'],
['Wednesday','10:30 AM','G','Robert Boedigheimer','Web','300','HTTP/2:  What You Need to Know'],
['Wednesday','10:30 AM','B','Jason Young','Cloud','200','IoT - Its Not Just a Buzzword'],
['Wednesday','10:30 AM','D','George Heeres','Mobile','200','JavaScript: You Dont Know Jack'],
['Wednesday','10:30 AM','Cypress','Stella Hu','Family','100','Mommy/Daddy & Me Circuit Art Workshop: Create Your Own Paper Crafts with Sticker Circuits'],
['Wednesday','10:30 AM','E','Matt Milner','Mobile','200','Notify your millions of campers with Notification Hubs'],
['Wednesday','10:30 AM','F','Nik Molnar','Web','200','Tracking Real World Web Performance'],
['Wednesday','10:30 AM','Portia','Joshua Warren','Other','100','Work-Life Balance For Passionate Developers'],
['Wednesday','1:00 PM','Portia','Brian Lewis','Cloud','100','A beginners guide to using PowerShell to manage Windows and Azure'],
['Wednesday','1:00 PM','F','Kelley Muir','Other','100','A UX Survival Guide Workshop for Developers'],
['Wednesday','1:00 PM','Tamarind','Mike Stowe','Web','400','Building Your API for Longevity'],
['Wednesday','1:00 PM','D','Jorge Coca','Mobile','200','Chromecast & Android: deliver an incredible experience from your smartphone to your TV'],
['Wednesday','1:00 PM','G','Angela Dugan','Other','100','Fear and (Self) Loathing in IT'],
['Wednesday','1:00 PM','B','Wyatt Webb','Other','200','Hiking through the Approval Test trail'],
['Wednesday','1:00 PM','Cypress','Savannah Boedigheimer','Family','200','Hour of Code for Campers'],
['Wednesday','1:00 PM','Marula','Ben Sykes','Other','400','Innovation Gaming : Perfecting Your Brainstorming Technique for Killer Products & Features'],
['Wednesday','1:00 PM','C','Ian Muir','Web','200','Lets Hack Another Website'],
['Wednesday','1:00 PM','Guava','Tim Miller','Mobile','200','Light up Your Campsite with Beacons'],
['Wednesday','1:00 PM','E','Mitch Muenster','Mobile','100','Mobile Design  for the Visually Aware Developer'],
['Wednesday','1:00 PM','Mangrove','William Wallace','Other','100','Save That Random Universe (ALL DAY)'],
['Wednesday','1:00 PM','Iron Wood','Benjamin Gavin','Family','300','That Robotics Lab - Day 2'],
['Wednesday','1:00 PM','Wisteria','Scott Davis','Mobile','200','Xamarin: cross platform beyond the generic buttons and text boxes'],
['Wednesday','2:30 PM','C','Vince Bullinger','Mobile','300','A Trek Through the Cross-Platform Forest with React Native'],
['Wednesday','2:30 PM','Marula','David Adsit','Other','300','Architectural Refactoring - Rebuilding an airplane in flight'],
['Wednesday','2:30 PM','D','Tugberk Ugurlu','Web','200','ASP.NET 5: How to Get Your Cheese Back'],
['Wednesday','2:30 PM','G','Jeremy Clark','Other','200','Clean Code: Homicidal Maniacs Read Code, Too!'],
['Wednesday','2:30 PM','B','Mike Grucella','Other','100','Coding Hangovers:  Avoid the regrets, headaches, and drowsiness brought on by hard-coded business logic'],
['Wednesday','2:30 PM','Tamarind','Lionel Barrow','Web','300','Evolving High Availability at Braintree'],
['Wednesday','2:30 PM','Guava','Brent Schooley','Web','100','Getting Fired Up About Ember.js 2.0'],
['Wednesday','2:30 PM','F','Emily Davis','Other','400','Intro to Programming with Text Adventure Games'],
['Wednesday','2:30 PM','Cypress','Katelyn Drew','Family','300','Koding for Kids 2.0: 3rd-5th grade'],
['Wednesday','2:30 PM','Portia','William Hoang','Mobile','400','Mobile Apps that Work in the Forest'],
['Wednesday','2:30 PM','E','Riley Major','Other','100','Open up the Clubhouse'],
['Wednesday','2:30 PM','Wisteria','Tony Blank','Other','400','Truth in Data Sharing'],
['Wednesday','4:00 PM','Mess Hall','Richard Campbell','That Conference','100','Closing Remarks']];